### ISSUE TITLE
PHP problem

### ISSUE THREAD

**Issue by salecz016** [xPh03n1x/Travian-T4.6-Gpack#1]
When i open imageDownloader.php in my browser i get error

Forbidden
You don't have permission to access this resource.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

Can u please help me how to import images?

**Comment by xPh03n1x** [comment]
From the mere fact that you are trying to load a PHP scripts in a browser as if it was an HTML file I can conclude that you don't have the sufficient understanding of PHP to utilize this script.

I suggest that you spend some time and get acquainted with PHP as a language. I am sorry but I am not going to teach you what PHP is and how to use it.
